### ISSUE TITLE
OptiFine breaks entity spawning

### ISSUE THREAD

**Issue by toErIpNid** [PolyhedralDev/Terra#166] opened 2021-05-08 00:34 UTC
Using the latest version of Terra as of May 7th, 2021. 7:30pm CST.

While seeing if the mod was usable for a world generator, I noticed while flying around in creative mod that no mobs seem to spawn besides one bee from a bee hive. No squids, no cows, no anything. Not even a witch in what seemed to be a witch-hut structure I found, nor any modded mobs such as snakes or birds from Bewitchment. Is this a bug?

**Comment by solonovamax** [comment] 2021-05-08 00:39
what platofrmplatform?

**Comment by Hexcede** [comment] 2021-05-08 19:40
Also see #139 I posted about this and proposed a fix. I am using the Fabric version though so if you are using the Bukkit version these could be different issues.

I think the issue is due to the fact that Terra doesn't actually copy biome data from the vanilla biomes so all of the biome-specific spawn settings and stuff are lost, it just copies from whatever the first biome happens to be which could very well just be "void" or "plains" or something.

Terra should be copying from alike biomes.

Jungles should copy from jungle data, otherwise ocelots won't spawn.
Plains should copy from plains data for better plains spawn rates.
Snowy biomes should copy from snowy biome data.
Mountain biomes like the craig biomes should copy from extreme hills or something.

This is why pandas and things just won't spawn ever at all, they're biome specific mobs so their spawn data _has_ to be copied and currently the mod doesn't do this.

**Comment by dfsek** [comment] 2021-05-08 19:47
I don't know why you think we are copying all spawn info from void biomes... look at the code again. 

I have consistently been unable to replicate this issue. Parrots and Ocelots spawn in jungles, rabbits spawn in deserts, pandas spawn in bamboo jungles, etc. This was all tested when I closed the previous issue. You probably updated an old world to a new version, in that case be sure to reset your world first.

**Comment by Hexcede** [comment] 2021-05-08 19:57
> I don't know why you think we are copying all spawn info from void biomes... look at the code again.
> 
> I have consistently been unable to replicate this issue. Parrots and Ocelots spawn in jungles, rabbits spawn in deserts, pandas spawn in bamboo jungles, etc. This was all tested when I closed the previous issue. You probably updated an old world to a new version, in that case be sure to reset your world first.

I apologize then, its good to hear this. 

This must have changed since I last looked or I missed it, because, I remember seeing biome data, specifically spawn data getting copied from `pathToBiomes.get(0)` or something along those lines. It may just be that the actual spawn data copying is done elsewhere from where I was looking as well.

Is there a way old worlds can be manually fixed? E.g. via an NBT editor? We're using this on a Fabric server and doing a world reset is not feasible but if it takes a little to change biome names or something then that's what I'll do.

Also, my issue wasn't closed, its different than the original one I was talking about before.

**Comment by dfsek** [comment] 2021-05-08 19:59
The issue was caused by heightmap data not being generated. If you really want to, you can make a tool to go through all your currently generated chunks and generate that data. Simply going to ungenerated chunks as well *should* work, albeit only in those ungenerated chunks.

**Comment by Hexcede** [comment] 2021-05-08 20:08
> The issue was caused by heightmap data not being generated. If you really want to, you can make a tool to go through all your currently generated chunks and generate that data. Simply going to ungenerated chunks as well _should_ work, albeit only in those ungenerated chunks.

Our specific issue isn't that mobs aren't spawning at all its that passive mobs are spawning incredibly slow and biome specific mobs didn't *seem* to be spawning, I think it took almost an hour before anyone found sheep and cows around and the rates of mobs spawning was super slow, it was taking a long time for things to respawn and stuff. Hostile mobs are handled globally iirc and we aren't having any problems with hostile mobs spawning.

Also, I found the specific line I was thinking of but again I probably missed something:
https://github.com/PolyhedralDev/Terra/tree/master/platforms/fabric/src/main/java/com/dfsek/terra/fabric/TerraFabricPlugin.java#L256
Line 290 is where the spawn settings from the first are applied.

**Comment by dfsek** [comment] 2021-05-08 20:13
https://github.com/PolyhedralDev/Terra/blob/fd48f5f110b2c664d1f177c08c1308bb057e368c/common/src/main/java/com/dfsek/terra/config/templates/BiomeTemplate.java#L76-L78

https://github.com/PolyhedralDev/TerraDefaultConfig/blob/7ebfecc64688eb18664c7887171902986132de8e/default/biomes/plains.yml#L15

That list does not contain *all* Vanilla biomes, just the biomes specified in the config. And in the case of the default config, the size of that list is always one. The option accepts a probability collection to allow merging of biome colors, and it takes the first biome in that collection to get spawn information from.

**Comment by Hexcede** [comment] 2021-05-08 20:31
> https://github.com/PolyhedralDev/Terra/blob/fd48f5f110b2c664d1f177c08c1308bb057e368c/common/src/main/java/com/dfsek/terra/config/templates/BiomeTemplate.java#L76-L78
> 
> https://github.com/PolyhedralDev/TerraDefaultConfig/blob/7ebfecc64688eb18664c7887171902986132de8e/default/biomes/plains.yml#L15
> 
> That list does not contain _all_ Vanilla biomes, just the biomes specified in the config. And in the case of the default config, the size of that list is always one. The option accepts a probability collection to allow merging of biome colors, and it takes the first biome in that collection to get spawn information from.

Cool. I'm misunderstanding the code then, sorry about that. Thank you.

If I generate a new world with the same seed, I am assuming I would be able to just copy the height map data for each chunk and the issue should be fixed, assuming we did generate the world in an older version?

**Comment by toErIpNid** [comment] 2021-05-09 00:24
> Also see #139 I posted about this and proposed a fix. I am using the Fabric version though so if you are using the Bukkit version these could be different issues.
> 
> I think the issue is due to the fact that Terra doesn't actually copy biome data from the vanilla biomes so all of the biome-specific spawn settings and stuff are lost, it just copies from whatever the first biome happens to be which could very well just be "void" or "plains" or something.
> 
> Terra should be copying from alike biomes.
> 
> Jungles should copy from jungle data, otherwise ocelots won't spawn.
> Plains should copy from plains data for better plains spawn rates.
> Snowy biomes should copy from snowy biome data.
> Mountain biomes like the craig biomes should copy from extreme hills or something.
> 
> This is why pandas and things just won't spawn ever at all, they're biome specific mobs so their spawn data _has_ to be copied and currently the mod doesn't do this.

I was using the fabric version.

**Comment by notken12** [comment] 2021-05-12 19:27
I'm experiencing this issue in my singleplayer survival world too. Also using the fabric version of the mod

**Comment by ShiDotMoe** [comment] 2021-05-13 15:25
Same issue on fabric singleplayer

**Comment by RiftScuttlermidalist** [comment] 2021-05-14 13:41
Same Issue on Paper Server.
Running latest version (Terra-Bukkit 5.3.1) on 1.16.5 paper server, new generated Map.
Passive animals like Cows, chicken and sheep are spawning normal. Hostile mobs like zombie, creeper also.
Only mobs not spawning are in structures like:
- Blazes and witherskeletons in nether fortress
- Pillager in Outpost
- small guardians in watermonuments (elder guardians do spawn)
- witch in witchhut
- Irongolem in Villages (do spawn at villager breeders)
- Ender dragon, enderman and shulker do spawn
probably many more, we haven't explored more at this point.

**Comment by dfsek** [comment] 2021-05-14 17:05
This is an incompatibility with OptiFine. We will not consider adding compatibility with OptiFine, as it does inexplicable things and is a closed-source mod, making working with it a nightmare.

**Closed by dfsek** 2021-05-14 17:05 UTC
Labels: Resolution: Wontfix

**Comment by dfsek** [comment] 2021-05-14 17:07
OptiFine should not be used on Fabric anyways - for alternatives (which will get you even greater performance improvements, and have most of the QOL features OptiFine does), see this Gist: https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754

**Comment by notken12** [comment] 2021-05-14 17:20
I have the same issue as RiftScuttlermidalist. Only squid, fish, dolphins, and hostile mobs are spawning but no passive mobs are spawning on land. I'm running a brand new fabric singleplayer world. I am not running Optifine.

**Comment by dfsek** [comment] 2021-05-14 21:19
Then open a new issue. This issue was caused by OptiFine, if you're having a similar issue, do more testing to figure out a possible cause and open a new issue.
