### ISSUE TITLE
World Stops Generating

### ISSUE THREAD

**Issue by Flamaxius952** [PolyhedralDev/Terra#172] opened 2021-05-10 11:39 UTC
So as of the latest forge beta, I get this weird issue where the world will stop generating properly on the 2nd time that you load up the world. Any new chunks generated at this point feature vanilla terrain generation and it conflicts heavily with the already generated modded terrain.

**Comment by dfsek** [comment] 2021-05-10 15:59
Duplicate of #168

**Closed by dfsek** 2021-05-10 15:59 UTC
Labels: Resolution: Duplicate
