### ISSUE TITLE
Outposts not spawning pillagers (fabric)

### ISSUE THREAD

**Issue by DUDEbehindDUDE** [PolyhedralDev/Terra#150] opened 2021-05-02 13:47 UTC
When i find a terra outpost pillagers don't spawn there like they are supposed to. I have also tried killing all the entities to make sure it's not because of the mob cap, but they just don't seem to be spawning.

**Comment by Astrashh** [comment] 2021-05-02 21:20
Not a bug, Terra just lacks the functionality for persistent mob spawning. #111 solves this.

**Comment by DUDEbehindDUDE** [comment] 2021-05-03 02:52
How long until it's finished

**Comment by solonovamax** [comment] 2021-05-03 19:09
nobody's working on it ATM, but if you want to, you can contribute code.

**Comment by dfsek** [comment] 2021-05-04 15:04
Duplicate of #111

**Closed by dfsek** 2021-05-04 15:04 UTC
Labels: Platform: All, Resolution: Duplicate, Type: Enhancement
