### ISSUE TITLE
Fabric/mod compat: Crash on Startup

### ISSUE THREAD

**Issue by AzureMonument** [PolyhedralDev/Terra#121] opened 2021-04-11 13:44 UTC
![image](https://user-images.githubusercontent.com/43318292/114306123-cda11000-9aa8-11eb-8de7-b7a1cdde9245.png)

I am running multiple mods, so I'm assuming this is a compat. I'm currently going through them to try and find what's causing it, but wanted to get this post started so I don't forget about it. Give me a sec...

Found it. It's apparently being caused by a mod called impersonate-2.1.0, a dependency for bewitchment. I'm currently running just it, Terra, and Fabric API and still crashing. The versions are as follows:
![image](https://user-images.githubusercontent.com/43318292/114306624-579da880-9aaa-11eb-8a24-8cd284139e47.png)

![image](https://user-images.githubusercontent.com/43318292/114306650-6a17e200-9aaa-11eb-89c7-d23af3a759f5.png)

I'll be checking for other mods shortly, but I'll post this first to get it started.

**Comment by AzureMonument** [comment] 2021-04-11 14:12
Okay, so I've been going through my mods, and there is a stupid amount of incompatibilities (at least in this version.)
I've had to remove 17 mods in total to get it to get to the main menu without crashing, and some of my most liked mods as well:
![image](https://user-images.githubusercontent.com/43318292/114307562-350d8e80-9aae-11eb-9f48-92f1cad7017f.png)

There may be a couple in there that aren't directly causing crashes, (notenoughcrashes I think may just be causing the crashes to loop when minecraft tries to load), but considering the current state of the mod and how it kills other mods I really like to use, I'll just be removing Terra from hence forth til' a later update. 

Anyway, thanks for the mod.

**Comment by AzureMonument** [comment] 2021-04-11 14:30
So removing spoornbountymobs, notenoughcrashes, and slabref causes the remaining mods to run on their own fine. Adding back terra afterwards still causes a crash. I'm gonna dig deeper. 
The game crashes with just bountymobs, clothconfig, and terra. bounty and cConfig run fine on their own, so that's one definite compat.

Anyway. I stand by my earlier point. I'm gonna try to get the game to run without any crashes then see about adding terra. Though if that fails I'll like just give up and wait for later 
Thanks for the mod.

**Comment by RDKRACZ** [comment] 2021-04-11 15:00
>slabref

You can try Full Slabs. Seems better, does more.

**Comment by solonovamax** [comment] 2021-04-11 16:00
Noticed you have CCA, so this might be similar to #102, as that crash is also caused by bytecode buffoonery.

**Comment by dfsek** [comment] 2021-04-12 00:51
Duplicate of #102

**Closed by dfsek** 2021-04-12 00:51 UTC
Labels: Platform: Fabric, Resolution: Duplicate, Type: Bug
