### ISSUE TITLE
Crash with Cardinal Components Entity

### ISSUE THREAD

**Issue by P03W** [PolyhedralDev/Terra#102] opened 2021-03-27 00:42 UTC
Environment:
- Fabric 1.16.5
- Single player tested personally, original crash report seems to be dedicated

Mods: 
- Fabric API 0.32.5
- RPGStats 3.2.4
- Terra 5.1.0-BETA

Attempting to load a world yields a crash similar to this one initially provided to me

[message.txt](https://github.com/PolyhedralDev/Terra/files/6214868/message.txt)

I'm not familiar with CCA's internals, but it seems like entities might be being created before CCA can properly bootstrap itself, hence the combination of missing classes and invalid stack, however that's just a guess

**Comment by solonovamax** [comment] 2021-03-27 22:04
What's a minimal reproducible example for this? Meaning, how can I reproduce this with the minimal amount of mods loaded?

**Comment by P03W** [comment] 2021-03-27 22:07
Ill attempt to create an example mod that can replace RPGStats in this example

**Comment by solonovamax** [comment] 2021-03-27 22:08
oh god.... is that a...... *bytecode exception*

**Comment by P03W** [comment] 2021-03-27 22:10
Yep, CCA is backed by custom ASM

Theres also some missing class exceptions for CcaBootstrap, which is a core class which definitely shouldn't be missing

**Comment by solonovamax** [comment] 2021-03-27 22:19
> Ill attempt to create an example mod that can replace RPGStats in this example

you don't need to do that, I just want to know do I *need* RPGStats loaded, or can I just load their test mod?

**Comment by P03W** [comment] 2021-03-27 22:26
I was unaware they had a test mod, yes that crashes, and *much* faster (the game window doesn't have a chance to appear)

Test mod (+ API, as its not bundled) crashes with [this](https://pastebin.com/SJf5jXWC) on launch

**Comment by solonovamax** [comment] 2021-03-29 14:33
I'll try and fuck around with it later & maybe submit an issue report on their end linking to this.

**Comment by dfsek** [comment] 2021-04-12 00:49
Just tested to verify, this is indeed caused by us shading a newer version of ASM for internal use and forgetting to relocate. This is fixed in 01d169256e0fb1260cc9c4f27e8098c0b2c1163f

**Closed** 2021-04-12 01:56 UTC
Labels: Platform: Fabric, Status: Pending, Subsystem: Internal API, Type: Bug
