### ISSUE TITLE
Crash With Trinkets Mod

### ISSUE THREAD

**Issue by toErIpNid** [PolyhedralDev/Terra#127] opened 2021-04-13 15:31 UTC
Fabric Version: 0.11.3

TWG Version: 5.1.1-BETA+c5800970

Trinkets Version: 2.6.7

Description: Game fails to launch.

Crash log: 
[crash-2021-04-13_10.27.51-client.txt](https://github.com/PolyhedralDev/Terra/files/6304866/crash-2021-04-13_10.27.51-client.txt)

**Comment by dfsek** [comment] 2021-04-13 15:32
Duplicate of #102. You are using an outdated version, update to the latest version of something before reporting issues.

**Closed by dfsek** 2021-04-13 15:32 UTC
